# -*- coding: utf-8 -*-
"""weights.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VAbnVlybUyEV-kRaZkNY3Yrk_DdnOi8F
"""

from google_drive_downloader import GoogleDriveDownloader as gdd
def download_weights():
    gdd.download_file_from_google_drive(file_id="1U6A1R3AO8HTeLKMmMAlx_D3dN7F09pVO",
                                        dest_path ="weights/food_weight.h5" )